//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppProj.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class StandingData
    {
        public StandingData()
        {
            this.DetailDatas = new HashSet<DetailData>();
            this.DetailDatas1 = new HashSet<DetailData>();
            this.DetailDatas2 = new HashSet<DetailData>();
            this.DetailDatas3 = new HashSet<DetailData>();
            this.DistrictByUserProfiles = new HashSet<DistrictByUserProfile>();
            this.DistrictDatas = new HashSet<DistrictData>();
            this.DistrictDatas1 = new HashSet<DistrictData>();
            this.DistrictSummeries = new HashSet<DistrictSummery>();
            this.DistrictSummeries1 = new HashSet<DistrictSummery>();
            this.HnppDatas = new HashSet<HnppData>();
            this.HnppDatas1 = new HashSet<HnppData>();
            this.SummerizedDatas = new HashSet<SummerizedData>();
            this.SummerizedDatas1 = new HashSet<SummerizedData>();
            this.SummerizedDatas2 = new HashSet<SummerizedData>();
        }
    
        public int Id { get; set; }
        public string Type { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> IntValue { get; set; }
        public string StringValue { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<int> ParentId { get; set; }
    
        public virtual ICollection<DetailData> DetailDatas { get; set; }
        public virtual ICollection<DetailData> DetailDatas1 { get; set; }
        public virtual ICollection<DetailData> DetailDatas2 { get; set; }
        public virtual ICollection<DetailData> DetailDatas3 { get; set; }
        public virtual ICollection<DistrictByUserProfile> DistrictByUserProfiles { get; set; }
        public virtual ICollection<DistrictData> DistrictDatas { get; set; }
        public virtual ICollection<DistrictData> DistrictDatas1 { get; set; }
        public virtual ICollection<DistrictSummery> DistrictSummeries { get; set; }
        public virtual ICollection<DistrictSummery> DistrictSummeries1 { get; set; }
        public virtual ICollection<HnppData> HnppDatas { get; set; }
        public virtual ICollection<HnppData> HnppDatas1 { get; set; }
        public virtual ICollection<SummerizedData> SummerizedDatas { get; set; }
        public virtual ICollection<SummerizedData> SummerizedDatas1 { get; set; }
        public virtual ICollection<SummerizedData> SummerizedDatas2 { get; set; }
    }
}
