//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppProj.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public UserProfile()
        {
            this.DetailDatas = new HashSet<DetailData>();
            this.DistrictByUserProfiles = new HashSet<DistrictByUserProfile>();
            this.DistrictDatas = new HashSet<DistrictData>();
            this.DistrictSummeries = new HashSet<DistrictSummery>();
            this.HnppDatas = new HashSet<HnppData>();
            this.SummerizedDatas = new HashSet<SummerizedData>();
        }
    
        public int Id { get; set; }
        public string Pin { get; set; }
        public string UserName { get; set; }
        public string EmailAddress { get; set; }
        public int RoleId { get; set; }
        public bool IsActive { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<DetailData> DetailDatas { get; set; }
        public virtual ICollection<DistrictByUserProfile> DistrictByUserProfiles { get; set; }
        public virtual ICollection<DistrictData> DistrictDatas { get; set; }
        public virtual ICollection<DistrictSummery> DistrictSummeries { get; set; }
        public virtual ICollection<HnppData> HnppDatas { get; set; }
        public virtual Role Role { get; set; }
        public virtual ICollection<SummerizedData> SummerizedDatas { get; set; }
    }
}
